# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-23 05:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Buglist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('content', models.TextField(max_length=2000, null=True, verbose_name='Buglist content')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_buglists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Buglists',
                'verbose_name': 'Buglist',
                'ordering': ['-created_at'],
            },
        ),
    ]
