# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-23 12:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('buglists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(choices=[('SW Version', 'SW Version'), ('HartBeat', 'HeartBeat'), ('ErrorCode', 'ErrorCode')], max_length=10, verbose_name='Type')),
                ('station', models.CharField(max_length=50, verbose_name='station')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'verbose_name': 'Station',
                'verbose_name_plural': 'Stations',
            },
        ),
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=300, null=True, verbose_name='message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'verbose_name': 'Tracker',
                'verbose_name_plural': 'Trackers',
            },
        ),
        migrations.AddField(
            model_name='buglist',
            name='status',
            field=models.CharField(choices=[('OPEN', 'OPEN'), ('CLOSE', 'CLOSE')], default='OPEN', max_length=5, verbose_name='status'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='buglist',
            name='content',
            field=models.TextField(max_length=2000, null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='tracker',
            name='buglist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items_tracker', to='buglists.Buglist', verbose_name='buglist'),
        ),
        migrations.AddField(
            model_name='tracker',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_tracker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='station',
            name='buglist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items_station', to='buglists.Buglist', verbose_name='buglist'),
        ),
    ]
