# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-23 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buglists', '0002_auto_20160723_1222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='types',
        ),
        migrations.AddField(
            model_name='buglist',
            name='types',
            field=models.CharField(choices=[('SW Version', 'SW Version'), ('HartBeat', 'HeartBeat'), ('ErrorCode', 'ErrorCode')], default='OPEN', max_length=10, verbose_name='Type'),
            preserve_default=False,
        ),
    ]
