# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-23 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buglists', '0003_auto_20160723_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='stationID',
            field=models.CharField(default='PGPD_F02-3FA-01_1_AE-16', max_length=50, verbose_name='stationid'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='station',
            name='station',
            field=models.CharField(max_length=20, verbose_name='station'),
        ),
    ]
