# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-23 13:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buglists', '0004_auto_20160723_1332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='station',
            old_name='stationID',
            new_name='stationid',
        ),
    ]
