# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-23 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buglists', '0005_auto_20160723_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='station',
        ),
        migrations.AddField(
            model_name='buglist',
            name='station',
            field=models.CharField(default='AAA', max_length=20, verbose_name='station'),
            preserve_default=False,
        ),
    ]
